{% set name = "pivottable" %}
{% set version = "2.19.0" %}
{% set sha256 = "3bf862e73b438ae920000b36ea1343b1175a961ecb97d05d0fc01af37edffdcd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nicolaskruchten/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g pivottable
  requires:
    - nodejs
   
about:
  home: https://github.com/nicolaskruchten/pivottable
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Open-source Javascript Pivot Table (aka Pivot Grid, Pivot Chart, Cross-Tab) implementation with drag and drop.'
  description: |
    PivotTable.js is a Javascript Pivot Table library with drag'n'drop 
    functionality built on top of jQuery/jQueryUI and originally written 
    in CoffeeScript by Nicolas Kruchten. 
  doc_url: https://github.com/nicolaskruchten/pivottable/wiki/Parameters
  dev_url: https://github.com/nicolaskruchten/pivottable
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
