travis:
  secure:
    BINSTAR_TOKEN: MwzJJzPd/+RlVouaTQ+PcVaE6z7mK8z5yqg/c6czqoNCwdysm0zqZysILJXybRafx9eNkQvxFZV05BvZjmJ2puSwt1b1CpgtnEAjv1SbDrIEjcWZqQgvHpg0gKk/6zZyuPMbygt35kR5GQFrwuZCMZRNoO9jA188kMmwrupTDQhxgF/bmucdypAihZkr7VeMsTX9CZqb28M6wjXTJPvNtRLavvjLfGDF/oF0OJ8YO36eSpw8j1994kTbXPK2XJbwGF/ahSOSTzjyTyw7XPPRtiCB8V9SiYcqrYFHPN3AWWZUEzwTLPEZqxFb6qbgRP5/WidhOWD1lKvxRfM24TVegE+08xFJ7UkRS8aslf7GuJbpdLnlS0QRd2dIOoUC3C9jmftCUHUotyjO638UyfoiK7dKUWz+UGHc7aaXqc6MD9eKYueV/nbbUZfZIBzfcADXeNhD69Y6zyCC6qc8s4HAUahjo6nzt/S5xjnsbzir1w3HBMwZwtSxKZRGc+vYd7vABadrRlg6hl4UB2YFPoqoBD6RJwKZTyA+Eqix0ni62wixNysYHEsAkppxyNKu2IvGNCXd+aDwsc2fxadNZmwfkys9OjcmwLg5apzyANSNBqORMQirAUc2sqzoUnXJ/efMYsMbBIASCywKeSHNbi7UGBDp7ROaMLIoAX5iLMyo1yE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
