travis:
  secure:
    BINSTAR_TOKEN: bmTWZY6H6u4XYEQvwEKodhA8Lt1V72ldNi05wjQky+z8LXJMPBTDD4F7rlGotnm6eLykCDvROmRaOvVoDS5LJl+C8JFyFwgtuZkvoATlZv2OROCmh9rZEUYWKikBENBDK+gY3sDe/7S3oJ2EPBiDBqmN7YQ4FRYAMyQI1agCLt4mv0TcHfh9m49BO5DtCxqLoPRTHGvLfV2JL1ayDStupgNx3W0XhNJJiewkjZoOI5e2rMZFxGt2kyjvDynK17NOx1HTWAbdsU09LR9+v5vwbhhFHWpKzfuins+bs9ix/qAVA425Q8qCEDvm/c9ny807fVoP0J1p88mNg/vQp8LF0nkbGJ6a0PzrMiJXJ5q9V2I4e0JkWdRVfNC9F4PgOX3s6tHHs2bc84rX8Hk1jaeuecatmK+YdiWZ6InykpqFUkz4BnMMVYo5+k+lTt3FfJRNZe/WUOZFbHHZku9Rh6KDwu/ncjU8xXKW1FnZSdCtNAEfWopeU9fCn/jnZPwi2lN1JIlNO7IeDM8Ki9EWPadiu+rf73OHZHHrtSgYfJT0gs2MhxMifTFnPmLnSSXZM67nJwzY0SHbqxuvdWDFsZ7CTj4xuIgG+LxjZDDVjFpmwiYZePHagXQkj8MBQrLCuQXkELq5WFSUf1D2JpHwx4PgIAyy70m7WfSzRqZRn0zK/d8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
